# Base
FROM python:3-onbuild

# Environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED=1

ENV SQL_DATABASE=postgres
ENV SQL_USER=django
ENV SQL_PASSWORD=djangopassword
ENV SQL_HOST=postgres
ENV SQL_POST=5432

# Port expose
EXPOSE 8000