version: '3.8'

services:
  web:
    build: .
    image: adamarutyunov/testapi
    command: >
        bash -c "python manage.py makemigrations && python manage.py migrate &&
          python CSVParser.py && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=djangopassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: